# see: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule: 
      interval: "weekly"
    ignore:
      - dependency-name: "pyqt5"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
