{
  "version": 1,
  "analyzers": [
      {
          "meta": {
              "max_line_length": 127,
              "runtime_version": "3.x.x"
          },
          "name": "python",
          "enabled": true
      }
  ],
  "exclude_patterns": [
      "doc/**"
  ]
}