repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-docstring-first
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
        args:
          - -d
          - --max-line-length 100
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
      - id: rst-backticks
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
