version: '{branch}.{build}'
# os: Windows
# image: Visual Studio 2015
branches:
  # whitelist tags schemes (e.g.: 1.0.0)
  only:
    - '/v\d.\d.\d/'
    - '/v\d*\.\d*\.\d*-.*/'

# Do build on tags
skip_non_tags: true
skip_branch_with_pr: true

# fetch repository as zip archive
# shallow_clone: true

# set clone depth, clone entire history if not defined
clone_depth: 5

skip_commits:
  files:
    - .deepsource.toml

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      APPVEYOR_REPO_TAG: true

cache:
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

install:
  - C:\cygwin\bin\du -hs '%LOCALAPPDATA%\pip\cache'
  # Add python and Scripts to the PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check version and architecture of python
  - python --version
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"

  # Install dependencies
  - python -m pip install --disable-pip-version-check --upgrade pip
  - python -m pip install pyinstaller
  - python -m pip install flake8
  - python -m pip install -r requirements.txt

before_test:
  - echo Starting Tests

after_test:
  - echo Finished Tests

test_script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

build_script:
  - c:\cygwin\bin\make qt
  - pyinstaller -F main.py

after_build:
  - ps: move dist\main.exe main.exe
  - 7z a qModManager.7z main.exe README.md LICENSE tools\

artifacts:
   - path: qModManager.7z
     name: qModManager

# clean up pip cache, might not be needed
on_finish:
  #- C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
  #- C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -size +10M -delete
  #- C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"

deploy:
  - provider: GitHub
    name: Github
    prerelease: true
    draft: false
    auth_token:
      secure: 9VzstVpyoCRNGlCcc9dIfoTYLTw9LBz5QDFkKg5qUqvT8Fk8bUTnOVSg5WCO7Fg7
    on:
      APPVEYOR_REPO_TAG: true
    artifact: qModManager
