name: Build

on:
  push:
    branches:
      - debug*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
    paths-ignore:
      - docs/**

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      PYTHON: "3.8"
    steps:
      - name: Define Release Type
        id: release_type
        run: |
          REF="${GITHUB_REF##*/}"
          if [[ $REF =~ "v"([0-9]\.)+[0-9] ]]; then
            echo ::set-output name=RELEASE_TYPE::release
          elif [[ $REF =~ "v"([0-9]\.)+[0-9]"-beta" ]]; then
            echo ::set-output name=RELEASE_TYPE::beta
          elif [[ $REF =~ "debug"("-".*)? ]]; then
            echo ::set-output name=RELEASE_TYPE::debug
          fi
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-cachepip-${{ hashFiles('qMM/requirements.txt') }}
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON }}
      - run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Building
        run: |
          make ui
          set PYTHONOPTIMIZE=1 && pyinstaller run.spec
      - name: Packaging
        run: |
          cd dist\qModManager\
          cp ..\..\CHANGELOG.rst CHANGELOG.txt
          7z a ..\..\qModManager-win64-${GITHUB_REF##*/}.7z . ..\..\resources\README.txt
      - name: Release (beta|debug)
        if: ${{ steps.release_type.outputs.RELEASE_TYPE != 'release' }}
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: qModManager-win64-${GITHUB_REF##*/}.7z
          prerelease: True
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Release (stable)
        if: ${{ steps.release_type.outputs.RELEASE_TYPE == 'release' }}
        uses: ncipollo/release-actionv1.8.6
        with:
          artifacts: qModManager-win64-${GITHUB_REF##*/}.7z
          token: ${{ secrets.GITHUB_TOKEN }}