name: Build

on:
  push:
    branches:
      - debug*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*


jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      PYTHON: "3.12"
    steps:
      - name: Define Release Type
        id: release_type
        run: |
          REF="${GITHUB_REF##*/}"
          if [[ $REF =~ "v"([0-9]\.)+[0-9]"-beta" ]]; then
            echo "RELEASE_TYPE=beta" >> $GITHUB_OUTPUT
          elif [[ $REF =~ "v"([0-9]\.)+[0-9]$ ]]; then
            echo "RELEASE_TYPE=release" >> $GITHUB_OUTPUT
          elif [[ $REF =~ "debug"("-".*)? ]]; then
            echo "RELEASE_TYPE=debug" >> $GITHUB_OUTPUT
          fi
          echo "VERSION=$REF" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Building
        run: |
          make ui
          set PYTHONOPTIMIZE=1 && pyinstaller run.spec
      - name: Packaging
        run: |
          cd dist/qModManager/
          cp ../../CHANGELOG.rst CHANGELOG.txt
          7z a ../../qModManager-win64-${GITHUB_REF##*/}.7z . ../../resources/README.txt
      - name: Release (debug)
        if: ${{ steps.release_type.outputs.RELEASE_TYPE == 'debug' }}
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: qModManager-win64-${{ steps.release_type.outputs.VERSION }}.7z
          prerelease: True
          token: ${{ secrets.GITHUB_TOKEN}}
          tag: ${{ steps.release_type.outputs.VERSION }}-${{ github.run_number }}
          body: |
            This is a debug build to help development.
      - name: Release (beta|debug)
        if: ${{ steps.release_type.outputs.RELEASE_TYPE == 'beta' }}
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: qModManager-win64-${{ steps.release_type.outputs.VERSION }}.7z
          prerelease: True
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Release (stable)
        if: ${{ steps.release_type.outputs.RELEASE_TYPE == 'release' }}
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: qModManager-win64-${{ steps.release_type.outputs.VERSION }}.7z
          token: ${{ secrets.GITHUB_TOKEN }}
