name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache pre-commit envs
        uses: actions/cache@v1
        env:
          cache-name: cache-precommit
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-lint-${{ env.cache-name }}-
            ${{ runner.os }}-lint-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install depedencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          python -m pip install --upgrade black==19.10b0

      - name: Lint
        run: pre-commit run --all-files
